//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS476.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int Userid { get; set; }
        public string email { get; set; }
        public string password_hash { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string username { get; set; }
        public System.DateTime eff_strt_dte { get; set; }
        public System.DateTime eff_end_dte { get; set; }
    }
}
